### PR TITLE
GCI making solutions in words

### PR DESCRIPTION
**Pull request by richarn**

### CODE REVIEW

**Comment by quozl** [comment]
@Pro-Panda, since you are working #3 at the moment, could you please review this stale pull request?

**Comment by rhl-bthr** [comment]
Sure

**Comment by richarn** [comment]
Sure, I an going to keep an eye about it these days

**Comment by rhl-bthr** [comment]
@richarn 
I agree that this PR is old, but please do the following:
 - Kindly use a more descriptive commit message
 - Please describe the changes you have made, along with the reason. I am finding it hard to spot the changes.

Thanks

**Comment by quozl** [comment]
Thanks for the review.  Here's mine;

* 082faf6 is a small change to add accents, by @ortegaps, so we could ask Pablo.
* 6c710b9 is an empty merge and can be ignored during squash.
* @walterbender as primary author may have some ideas.
* of possible interest also is c1e4bf5 by @kridix in a fork without pull request.

----

Word by word change detection is a useful skill, and GitHub only shows line by line changes; here's what I did in a clone;

### get the pull request commits without cloning the fork

```
git fetch origin pull/85/head
```

### verify that the merge commit is not needed

```
git diff 082faf6..6c710b9
```

### word by word diff of 082faf6

```
git diff --word-diff=color master..082fa
```

Change is to accent characters.

**Comment by rhl-bthr** [comment]
@quozl Thanks for the explanation on word by word reviewing

Will wait for a consensus from @walterbender, @ortegaps and @kiridix on 082faf6 and c1e4bf5

**Comment by walterbender** [comment]
The changes look good. I am having an unrelated display issue when running from Fedora using sugar-activity, which I will write up in a separate issue.

**Comment by richarn** [comment]
Hi I was out for a long time, Is there something that I could do? I got
enough time now

2018-02-28 15:22 GMT-03:00 Rahul Bothra <notifications@github.com>:

**Comment by quozl** [comment]
Thanks for asking.  Your contribution was merged while you were out.  Nothing further needed on the change itself.

If you have time to work on something new, please do so.  There's plenty to do.  Check https://github.com/sugarlabs and click on projects, check repositories for issues, or ask on sugar-devel@ or IRC #sugar.  There's also a [How to get started as a Sugar Labs developer](http://lists.sugarlabs.org/archive/sugar-devel/2018-April/055284.html).

**Comment by richarn** [comment]
OK! thanks, I will keep an eye to contribuit

2018-05-08 2:47 GMT-04:00 James Cameron <notifications@github.com>:

**Pull request merged**
