### PR TITLE
Migrate documentation from Wiki

### PR DESCRIPTION
**Pull request by vipulgupta2048**
This PR migrates wiki-pages of I-can-read Activity from https://wiki.sugarlabs.org/go/Activities/I_can_read [1]

**Description** 
1. The PR migrates all documentation from i-can-read activity (including images) from the wiki-page [1] to GitHub flavored Markdown in the repository using a script with minimum interventions from user.

**In reference to** - Project on Migration of wiki Activity pages to git [[WikiPort](https://wiki.sugarlabs.org/go/WikiPort)]

**To-do** 
- [ ] When PR is merged; Delete [1] and all images associated with it. [Using Pywikibot or MediaWiki API]

- [ ] While doing research, I found 2 pages for the same activity ([1] is the original and there is another page[2] which redirects to [1] again.) [2] needs to be deleted to maintain consistency.
[2] - https://wiki.sugarlabs.org/go/Activities/Icanread

**Status** - Complete

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@quozl @Pro-Panda  I think I implemented all the changes we discussed in the previous PR (Closed that)
 Please review if any other changes are needed. If no; then I can make the same changes for other pull requests made and discuss the To-Do task in the description.

**Comment by quozl** [comment]
Thanks.

**Comment by vipulgupta2048** [comment]
@quozl **Update** 
- I have updated, fixed and added the changes requested into the remaining three interlinked PR's for activity pages namely  
1. https://github.com/sugarlabs/AEIOU/pull/9
2. https://github.com/sugarlabs/iknowmyabcs/pull/7
3. https://github.com/sugarlabs/lettermatch/pull/3
- Also, added another task to PR description. 
- Continue the discussion on the method of deleting wiki-pages and linking them here.

**Comment by rhl-bthr** [comment]
Seems good to me. 
Although I am unsure of the name `docs` for storing the images. Would `images` be a better alternative ? (If it already exists, you may add more images to the same)

**Comment by quozl** [comment]
`images` is often used by the activity for holding PNG or SVG files, and `icons` often used for SVG files.  By separating files used by the activity from documentation, it could be simpler.  I've not made an audit though.

**Comment by rhl-bthr** [comment]
Thank you, I went through a few activities' structures. I agree

**Comment by vipulgupta2048** [comment]
I actually thought of that but then it is not cool to mess around with someone's else directory structure. So I first thought of assets, but then docs is a better name for it on discussion with @quozl. 

Any ideas why they are separate entries of the same activities redirecting to them

**Comment by vipulgupta2048** [comment]
@quozl Any more changes that need to be implemented here? If not then this and other PR's are ready to merge.

**Comment by rdrsadhu** [comment]
shouldn't the help-activity be a better place to put all these documentation ?
because the information all these pages contain, is more inclined towards a sugar-user (students/teachers/anyone) than a sugar-developer

also, putting these stuff in the help-activity makes it available when an user searches for contextual help(by pressing alt+shift+h) from within another activity

We could then create a README in the individual repositories, which point to this user documentation

I've made a [PR](https://github.com/godiard/help-activity/pull/41) accordingly.

**Comment by quozl** [comment]
Indeed, it is because we have two competing pull-requests that I'm joyfully delaying merge until I see consensus.  Both pull-requests have merit. https://github.com/sugarlabs/i-can-read-activity/pull/6 vs https://github.com/godiard/help-activity/pull/41.

**Comment by vipulgupta2048** [comment]
@quozl I never believed in competition in open-source, because there is none. Contributing and working with the community, is all that I have in mind and everybody else here should too. I think @rdrsadhu's PR does make sense and have its own merits just like mine. The decision to merge the PR and which PR is with the maintainers, so I will leave it at that.

**Comment by vipulgupta2048** [comment]
Regarding **reaching** a consensus, I have shared links of the checklist [1] **both** on the mailing list and on #4 but received no form information from other contributors about the project. If I would have known earlier about the PR's to [godiard/help-activity](https://github.com/godiard/help-activity) then this wouldn't have happened in the first place. I also would have tried and fixed my errors when I was working on #4 (where all contributors were mentioned by @quozl)
I want to work collaboratively with others. I will continue to do so for the community and accept any mistakes that I might have committed wholeheartedly.  
[1] -  https://gist.github.com/vipulgupta2048/29eb0cbb6c9d294d52d9554a30f8f724 (Most recent)

**Comment by quozl** [comment]
In godiard/help-activity#41 and this pull request, at the moment, consensus I'm looking for is whether the _content_ proposed for merging should be added to the activity repository or the Help activity.  Added reviewers.

**Comment by rdrsadhu** [comment]
Merged at https://github.com/godiard/help-activity/pull/41
should be closed.

**Pull request closed without merging**
