### PR TITLE
Fixing files for deployment of ASLOv3

### PR DESCRIPTION
**Pull request by vipulgupta2048**
In reference to the project in GSoC 2018,
For the successful deployment of ASLOv3, some files and activity.info need to be added/fixed/updated to present correct metadata on the website.

Updated Parameters:-
1. `website`
2. `repository`
3. `summary`
4. Changed `category` to `tags`

Please review the same, and suggest any changes that are required.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
The merge commit arose as I forgot to remove the previous unmerged commit from PR #6

**Comment by rhl-bthr** [comment]
Thanks. Reviewed. 

> The merge commit arose as I forgot to remove the previous unmerged commit from PR #6

Please fix the same and force push again

**Comment by vipulgupta2048** [comment]
Implemented. Thanks @Pro-Panda

**Comment by rhl-bthr** [comment]
Thanks

**Comment by quozl** [comment]
Not important enough to change now, but note the missing newline at the end of the file.  No functional impact, but is disturbing for people using a CLI to display the file.

**Comment by rhl-bthr** [comment]
Noted. Thank you

**Pull request merged**
